version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - db-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: gin_db
    restart: unless-stopped
    volumes:
      - ../storage:/var/lib/postgresql/data
    networks:
      - db-network
    expose:
      - 5432
    env_file:
      - .env

networks:
  db-network:
    driver: bridge